version: "3"
services:
  flask:
    build: .
    image: flask_app
    ports:
      - 5000:5000
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://user:hello_world@db:5432/bookkeeper
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=hello_world
      - POSTGRES_DB=bookkeeper
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  migrator:
    image: flask_app
    environment:
    - DATABASE_URL=postgres://user:hello_world@db:5432/bookkeeper
    # override CMD of the Dockerfile
    command: python migrate.py
    volumes:
    - ./migrate.py:/app/migrate.py
    - ./books.csv:/app/books.csv


volumes:
  postgres_data:
